<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P1CM33A" failures="1" tests="12" name="ExtentReport.Facebook_Login" time="0.372" errors="0" timestamp="2024-08-24T12:04:46 IST" skipped="5">
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_posts" time="0.035"/>
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Login" time="0.028">
    <skipped/>
  </testcase> <!-- faceBook_Login -->
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Login" time="0.028">
    <skipped/>
  </testcase> <!-- faceBook_Login -->
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Notification" time="0.018"/>
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Login" time="0.030">
    <skipped/>
  </testcase> <!-- faceBook_Login -->
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Login" time="0.071">
    <skipped/>
  </testcase> <!-- faceBook_Login -->
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Profile" time="0.033"/>
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Registration" time="0.023"/>
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_TimeLine" time="0.019"/>
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Login" time="0.021">
    <failure message="expected [400] but found [300]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [300]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at ExtentReport.Facebook_Login.faceBook_Login(Facebook_Login.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- faceBook_Login -->
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_Login" time="0.034">
    <skipped/>
  </testcase> <!-- faceBook_Login -->
  <testcase classname="ExtentReport.Facebook_Login" name="faceBook_HomePage" time="0.032"/>
</testsuite> <!-- ExtentReport.Facebook_Login -->
